# Bina 

## Fragestellung

Inwieweit lassen sich Gesundheitskosten in der Schweiz durch demografische (insbesondere Altersstruktur) und regionale Faktoren erklären und welche Segmente verursachen die grösste Systembelastung?

1. Wie entwickeln sich die Gesundheitskosten über die Zeit?
2. Wie unterscheiden sich Kosten nach Alter und Region?
3. Welchen Anteil haben ältere Altersgruppen (65+) an den Gesamtkosten und wie verändert sich dieser über die Zeit?
4. Lassen sich auf Basis von Altersstruktur und Kosten klare Segmente (Cluster) identifizieren?
5. Welche Faktoren erklären die Unterschiede zwischen diesen Segmenten und welche sollten priorisiert werden?

Ziel ist es, datenbasierte Entscheidungsgrundlagen für die Priorisierung von Massnahmen im Gesundheitssystem abzuleiten.

In [45]:
import pandas as pd 
import numpy as np

## Dataset

[Link](https://www.bfs.admin.ch/asset/de/DF_COU_HEALTH_COSTS)

In [46]:
df = pd.read_csv("data/gesuntheitskosten.csv")
df.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,P,Service provider,S,Service,M,Mode of provision,...,DIFF_DB_STATE,Database state,MULT,Unit Multiplier,OBS_STATUS,Code list for Observation Status,DECIMALS,Decimals,DIFF_REGION_REF,Spatial reference
0,DATAFLOW,CH1.COU:DF_COU_HEALTH_COSTS(1.0.0),Costs of health care,I,_T,Total,S_1_4_2,"Acute and transitional care (ATC), psychiatric",_T,Total,...,2025-03-31,NaN,0,Units,A,Normal value,3,Three,KANT,Cantons
1,DATAFLOW,CH1.COU:DF_COU_HEALTH_COSTS(1.0.0),Costs of health care,I,_T,Total,S_1_4_2,"Acute and transitional care (ATC), psychiatric",_T,Total,...,2025-03-31,NaN,0,Units,A,Normal value,3,Three,KANT,Cantons
2,DATAFLOW,CH1.COU:DF_COU_HEALTH_COSTS(1.0.0),Costs of health care,I,_T,Total,S_1_4_2,"Acute and transitional care (ATC), psychiatric",_T,Total,...,2025-03-31,NaN,0,Units,A,Normal value,3,Three,KANT,Cantons
3,DATAFLOW,CH1.COU:DF_COU_HEALTH_COSTS(1.0.0),Costs of health care,I,_T,Total,S_1_4_2,"Acute and transitional care (ATC), psychiatric",_T,Total,...,2025-03-31,NaN,0,Units,A,Normal value,3,Three,KANT,Cantons
4,DATAFLOW,CH1.COU:DF_COU_HEALTH_COSTS(1.0.0),Costs of health care,I,_T,Total,S_1_4_2,"Acute and transitional care (ATC), psychiatric",_T,Total,...,2025-03-31,NaN,0,Units,A,Normal value,3,Three,KANT,Cantons

## Data Details

In [47]:
print(f'columns: \n {df.columns}')
print(f'shape: \n {df.shape}')

columns:
 Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'P',
       'Service provider', 'S', 'Service', 'M', 'Mode of provision', 'F',
       'Financing scheme', 'AGE', 'Age groups', 'GENDER', 'Sex', 'CANTON',
       'Swiss cantons', 'UNIT', 'Measurement unit', 'FREQ', 'Frequency',
       'TIME_PERIOD', 'Time Period', 'OBS_VALUE',
       'Observation value (DotStat)', 'DIFF_REGION_STATE',
       'Date of spatial reference', 'DIFF_LAST_UPDATE', 'Update date',
       'DIFF_EMBARGO_DATE', 'Date of publication', 'DIFF_DB_STATE',
       'Database state', 'MULT', 'Unit Multiplier', 'OBS_STATUS',
       'Code list for Observation Status', 'DECIMALS', 'Decimals',
       'DIFF_REGION_REF', 'Spatial reference'],
      dtype='str')
shape:
 (5804640, 42)

In [48]:
cols_to_check = [
    "P", "Service provider",
    "S", "Service",
    "M", "Mode of provision",
    "F", "Financing scheme",
    "AGE", "Age groups",
    "GENDER", "Sex",
    "CANTON", "Swiss cantons",
    "TIME_PERIOD",
    "UNIT", "Unit Multiplier",
]

for col in cols_to_check:
    print(f"\n{col}:")
    print(df[col].unique()[:10])

P:
<StringArray>
[     '_T',   'P_1_1',     'P_1', 'P_3_2_2',   'P_3_5', 'P_1_2_3',   'P_1_2',
   'P_3_1',     'P_2',  'P_3_11']
Length: 10, dtype: str

Service provider:
<StringArray>
[                      'Total',      'General care hospitals',
                   'Hospitals',   'University dental clinics',
     'Occupational therapists',            'Birthing centres',
         'Specialized clinics',           'Medical practices',
 'Social medical institutions',          'Home care services']
Length: 10, dtype: str

S:
<StringArray>
['S_1_4_2', 'S_1_3_2', 'S_5_2_3',      '_T',     'S_1',   'S_1_1', 'S_1_1_1',
 'S_1_1_2',   'S_1_2', 'S_1_2_1']
Length: 10, dtype: str

Service:
<StringArray>
['Acute and transitional care (ATC), psychiatric',
                    'Long-term care, psychiatric',
                            'Prevention: Testing',
                                          'Total',
                                           'Care',
                                  'Curative care',
                         'Curative care, somatic',
                     'Curative care, psychiatric',
                            'Rehabilitative care',
                   'Rehabilitative care, somatic']
Length: 10, dtype: str

M:
<StringArray>
['_T', 'M_1', 'M_3', 'M_5', 'M_2', 'M_4']
Length: 6, dtype: str

Mode of provision:
<StringArray>
['Total', 'Inpatient', 'Day care', 'Not defined', 'Outpatient', 'Home based']
Length: 6, dtype: str

F:
<StringArray>
[   '_T', 'F_4_3', 'F_3_1', 'F_2_3', 'F_4_2', 'F_4_1', 'F_2_4',   'F_3',
   'F_5', 'F_2_2']
Length: 10, dtype: str

Financing scheme:
<StringArray>
[                              'Total',  'Self-payments without cost sharing',
                   'Private insurance',                'Disability insurance',
 'Self-payments, private cost sharing',  'Self-payments, social cost sharing',
                  'Accident insurance',                   'Private financing',
           'Financing schemes unknown',     'Old age and survivors insurance']
Length: 10, dtype: str

AGE:
<StringArray>
['Y41T45', 'Y46T50', 'Y61T65', 'Y91T95', 'Y86T90', 'Y51T55', 'Y66T70',
   'Y0T5', 'Y26T30', 'Y31T35']
Length: 10, dtype: str

Age groups:
<StringArray>
['41-45 years', '46-50 years', '61-65 years', '91-95 years', '86-90 years',
 '51-55 years', '66-70 years',   '0-5 years', '26-30 years', '31-35 years']
Length: 10, dtype: str

GENDER:
<StringArray>
['1', '2', '_T']
Length: 3, dtype: str

Sex:
<StringArray>
['Male', 'Female', 'Total']
Length: 3, dtype: str

CANTON:
<StringArray>
['24', '22', '15', '6', '_T', '25', '1', '9', '26', '13']
Length: 10, dtype: str

Swiss cantons:
<StringArray>
[             'Neuchâtel',                   'Vaud', 'Appenzell Ausserrhoden',
               'Obwalden',                  'Total',                 'Geneva',
                 'Zurich',                    'Zug',                   'Jura',
       'Basel-Landschaft']
Length: 10, dtype: str

TIME_PERIOD:
[2018 2019 2020 2021 2022 2023 2010 2011 2012 2013]

UNIT:
<StringArray>
['CHF_R_POP_R_MH', 'CHF']
Length: 2, dtype: str

Unit Multiplier:
<StringArray>
['Units', 'Millions']
Length: 2, dtype: str

In [49]:
for series_name, series in df.items():
    print(f'{series_name}: {series.nunique()}')

STRUCTURE: 1
STRUCTURE_ID: 1
STRUCTURE_NAME: 1
ACTION: 1
P: 62
Service provider: 62
S: 43
Service: 43
M: 6
Mode of provision: 6
F: 22
Financing scheme: 22
AGE: 21
Age groups: 21
GENDER: 3
Sex: 3
CANTON: 27
Swiss cantons: 27
UNIT: 2
Measurement unit: 2
FREQ: 1
Frequency: 1
TIME_PERIOD: 65
Time Period: 0
OBS_VALUE: 399790
Observation value (DotStat): 0
DIFF_REGION_STATE: 1
Date of spatial reference: 0
DIFF_LAST_UPDATE: 1
Update date: 0
DIFF_EMBARGO_DATE: 1
Date of publication: 0
DIFF_DB_STATE: 1
Database state: 0
MULT: 2
Unit Multiplier: 2
OBS_STATUS: 3
Code list for Observation Status: 3
DECIMALS: 1
Decimals: 1
DIFF_REGION_REF: 1
Spatial reference: 1

In [50]:
df["AGE"].value_counts().head(10)

AGE
_T        750240
Y41T45    252720
Y46T50    252720
Y61T65    252720
Y91T95    252720
Y86T90    252720
Y51T55    252720
Y66T70    252720
Y0T5      252720
Y26T30    252720
Name: count, dtype: int64

In [51]:
df[["OBS_VALUE", "MULT"]].describe()

          OBS_VALUE       MULT
count  5.804640e+06  5804640.0
mean   6.590772e+01        3.0
std    4.842617e+02        3.0
min    0.000000e+00        0.0
25%    1.390000e-01        0.0
50%    2.109000e+00        3.0
75%    1.534700e+01        6.0
max    9.707637e+04        6.0

## Some Data Cleanup

In [52]:

df_filtered = df[
    (df["P"] == "_T") &
    (df["S"] == "_T") &
    (df["M"] == "_T") &
    (df["F"] == "_T") &
    (df["GENDER"] == "_T")
].copy()

df_filtered = df_filtered[
    [
        "CANTON",
        "Swiss cantons",
        "AGE",
        "Age groups",
        "TIME_PERIOD",
        "OBS_VALUE",
        "MULT",
        "Measurement unit",
        "OBS_STATUS",
        "Code list for Observation Status",
    ]
].copy()

df_filtered = df_filtered.rename(
    columns={
        "CANTON": "canton",
        "Swiss cantons": "canton_name",
        "AGE": "age_code",
        "Age groups": "age_label",
        "TIME_PERIOD": "year",
        "OBS_VALUE": "costs_raw",
        "MULT": "mult",
        "Measurement unit": "measurement_unit",
        "OBS_STATUS": "obs_status",
        "Code list for Observation Status": "obs_status_label",
    }
)

df_filtered["year"] = pd.to_numeric(df_filtered["year"], errors="coerce").astype("Int64")
df_filtered["costs_raw"] = pd.to_numeric(df_filtered["costs_raw"], errors="coerce")
df_filtered["mult"] = pd.to_numeric(df_filtered["mult"], errors="coerce")

df_filtered["costs"] = df_filtered["costs_raw"] * (10 ** df_filtered["mult"])

df_filtered = df_filtered.reset_index(drop=True)

print(df_filtered.shape)
display(df_filtered.head())

(15978, 11)

,canton,canton_name,age_code,age_label,year,costs_raw,mult,measurement_unit,obs_status,obs_status_label,costs
0,6,Obwalden,Y56T60,56-60 years,2010,16.131,6,Swiss franc,A,Normal value,16131000.0
1,6,Obwalden,Y56T60,56-60 years,2011,17.088,6,Swiss franc,A,Normal value,17088000.0
2,6,Obwalden,Y56T60,56-60 years,2012,18.008,6,Swiss franc,A,Normal value,18008000.0
3,6,Obwalden,Y56T60,56-60 years,2013,19.024,6,Swiss franc,A,Normal value,19024000.0
4,6,Obwalden,Y56T60,56-60 years,2014,19.688,6,Swiss franc,A,Normal value,19688000.0

### Validation and fixing fails

In [53]:
check = (
    df_filtered
    .groupby(["canton", "year", "age_code"])
    .size()
)

check.value_counts()

2    7989
Name: count, dtype: int64

In [54]:
df_filtered.groupby(
    ["canton", "year", "age_code"]
)["obs_status"].nunique().value_counts()

obs_status
1    7989
Name: count, dtype: int64

In [55]:
df_filtered.columns.tolist()

['canton',
 'canton_name',
 'age_code',
 'age_label',
 'year',
 'costs_raw',
 'mult',
 'measurement_unit',
 'obs_status',
 'obs_status_label',
 'costs']

In [56]:
cols_to_test = [
    'canton',
    'canton_name',
    'age_code',
    'age_label',
    'year',
    'costs_raw',
    'mult',
    'measurement_unit',
    'obs_status',
    'obs_status_label',
    'costs'
 ]

for col in cols_to_test:
    test = (
        df_filtered
        .groupby(["canton", "year", "age_code"])[col]
        .nunique()
        .value_counts()
    )
    print(f"\n{col}:")
    print(test)

canton:
canton
1    7989
Name: count, dtype: int64

canton_name:
canton_name
1    7989
Name: count, dtype: int64

age_code:
age_code
1    7989
Name: count, dtype: int64

age_label:
age_label
1    7989
Name: count, dtype: int64

year:
year
1    7989
Name: count, dtype: int64

costs_raw:
costs_raw
2    7989
Name: count, dtype: int64

mult:
mult
2    7989
Name: count, dtype: int64

measurement_unit:
measurement_unit
2    7989
Name: count, dtype: int64

obs_status:
obs_status
1    7989
Name: count, dtype: int64

obs_status_label:
obs_status_label
1    7989
Name: count, dtype: int64

costs:
costs
2    7989
Name: count, dtype: int64

In [57]:
df_filtered["measurement_unit"].value_counts()

measurement_unit
Swiss franc                     7989
CHF per capita and per month    7989
Name: count, dtype: int64

In [58]:
df_filtered = df_filtered[
    df_filtered["measurement_unit"] == "Swiss franc"
].copy()

In [59]:
df_filtered.groupby(["canton", "year", "age_code"]).size().value_counts()

1    7989
Name: count, dtype: int64

## Some more Data cleaning

In [60]:
df_detail = df_filtered[
    (df_filtered["canton"] != "_T") &
    (df_filtered["age_code"] != "_T")
].copy()

df_canton_total = df_filtered[
    (df_filtered["canton"] != "_T") &
    (df_filtered["age_code"] == "_T")
].copy()

df_total = df_filtered[
    (df_filtered["canton"] == "_T") &
    (df_filtered["age_code"] == "_T")
].copy()

age_order = [
    "0-5 years", "6-10 years", "11-15 years", "16-20 years",
    "21-25 years", "26-30 years", "31-35 years", "36-40 years",
    "41-45 years", "46-50 years", "51-55 years", "56-60 years",
    "61-65 years", "66-70 years", "71-75 years", "76-80 years",
    "81-85 years", "86-90 years", "91-95 years", "96 years or older"
]

## First Plots

In [61]:
import plotly.io as pio
pio.renderers.default = "browser"

In [62]:
import plotly.express as px

px.line(
    df_total,
    x="year",
    y="costs",
    title="Gesamte Gesundheitskosten Schweiz"
)

In [63]:
df_age = (
    df_detail
    .groupby("age_label", as_index=False)["costs"]
    .mean()
)

px.bar(
    df_age,
    x="age_label",
    y="costs",
    category_orders={"age_label": age_order},
    title="Kosten nach Altersgruppe"
)

In [64]:
# TODO: Order Age correctly

pivot = df_detail.pivot_table(
    index="age_label",
    columns="year",
    values="costs",
    aggfunc="mean",
)

px.imshow(pivot, aspect="auto",
          title="Kosten nach Jahr und Altersgruppe",     
)

In [65]:
df_canton = (
    df_canton_total
    .groupby("canton_name", as_index=False)["costs"]
    .mean()
    .sort_values("costs", ascending=False)
)

px.bar(df_canton.head(10), x="canton_name", y="costs", title="Kosten pro Kanton (Top 10)")

In [66]:
df_age_total = (
    df_detail
    .groupby("age_label", as_index=False)["costs"]
    .sum()
)

In [67]:
df_age_total["share"] = df_age_total["costs"] / df_age_total["costs"].sum()

In [68]:
px.bar(df_age_total, x="age_label", 
       y="share", category_orders={"age_label": age_order}, 
       title="Anteil der Kosten pro Altergruppe (%)")

In [69]:
df_age_time = (
    df_detail
    .groupby(["year", "age_label"])["costs"]
    .sum()
    .reset_index()
)

In [70]:
px.line(df_age_time, x="year", y="costs", color="age_label", category_orders={"age_label": age_order})

In [71]:
df_detail["age_start"] = df_detail["age_label"].str.extract(r"(\d+)").astype(int)
df_detail["is_65_plus"] = df_detail["age_start"] >= 65

df_65 = (
    df_detail
    .groupby(["year", "is_65_plus"])["costs"]
    .sum()
    .reset_index()
)
df_65_total = df_65.groupby("year")["costs"].transform("sum")
df_65["share"] = df_65["costs"] / df_65_total

In [72]:
df_65_plus = df_65[df_65["is_65_plus"]].copy()
df_65_plus["share_pct"] = df_65_plus["share"] * 100

px.line(
    df_65_plus,
    x="year",
    y="share_pct",
    title="Anteil der Gesundheitskosten durch 65+ (%)"
)

### Validation to explain dip

There is a weird dip in 2021. Check to see if it's a fail or maybe Corona

In [73]:
df_total_manual = (
    df_detail
    .groupby("year", as_index=False)["costs"]
    .sum()
    .rename(columns={"costs": "costs_manual"})
)

df_total_official = (
    df_total[["year", "costs"]]
    .rename(columns={"costs": "costs_official"})
)

df_compare = df_total_manual.merge(
    df_total_official,
    on="year",
    how="inner"
)

df_compare["diff"] = df_compare["costs_manual"] - df_compare["costs_official"]
df_compare["rel_diff_pct"] = df_compare["diff"] / df_compare["costs_official"] * 100

df_compare

    year  costs_manual  costs_official     diff  rel_diff_pct
0   2010  6.239695e+10    6.239696e+10 -13000.0     -0.000021
1   2011  6.423461e+10    6.423460e+10   4000.0      0.000006
2   2012  6.652148e+10    6.652148e+10   2000.0      0.000003
3   2013  6.935247e+10    6.935248e+10  -9000.0     -0.000013
4   2014  7.105556e+10    7.105556e+10   7000.0      0.000010
5   2015  7.334597e+10    7.334597e+10   5000.0      0.000007
6   2016  7.593587e+10    7.593588e+10  -3000.0     -0.000004
7   2017  7.786658e+10    7.786658e+10  -6000.0     -0.000008
8   2018  7.917165e+10    7.917164e+10   5000.0      0.000006
9   2019  8.168612e+10    8.168611e+10   2000.0      0.000002
10  2020  8.352202e+10    8.352201e+10   7000.0      0.000008
11  2021  8.909925e+10    8.909926e+10 -10000.0     -0.000011
12  2022  9.175915e+10    9.175915e+10  -2000.0     -0.000002
13  2023  9.395227e+10    9.395227e+10  -5000.0     -0.000005

In [74]:
df_total["costs"]

3052    2.002302e+09
3053    2.125356e+09
3054    2.306351e+09
3055    2.486924e+09
3056    2.750276e+09
            ...
3112    8.352201e+10
3113    8.909926e+10
3114    9.175915e+10
3115    9.395227e+10
3116    9.707637e+10
Name: costs, Length: 65, dtype: float64

## Additional Dataset

We need info about the population, to make sure the where the real cost is. There are fewer 96+ people -> cost per person could be higher

[Link](https://www.bfs.admin.ch/bfs/de/home/statistiken/bevoelkerung.assetdetail.36074768.html)

## Add some Machine learning

Time for more cleaning, one hot encoding, feature engineering etc

- K-Means for groups
- RandoForest for feature importance